steps:
# Build the container for cart
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cart', '.']
  dir: 'src'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cart']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cart', '--image', 'gcr.io/$PROJECT_ID/cart', '--region', '$_REGION','--vpc-connector','vpc-connector','--vpc-egress','all','--update-env-vars','mongohost=10.132.0.2,mongoport=27017,MONGO_USERNAME=appuser,MONGO_PASSWORD=apppwd']
images:
- gcr.io/$PROJECT_ID/cart
